name: Nightly Release Action
on:
  push:
    branches: [ master ]

jobs:
  Create-Release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout v3
      uses: actions/checkout@v3

    - name: Setup NodeJs
      uses: actions/setup-node@v3
      with:
        node-version: 16
        #cache: 'npm'

    - name: Install Deps
      run: npm ci

    - name: Modify Configuration For Production
      run: node ./modifyConfig.js --disableInspector --versionFromPkgJson

    - name: Build
      run: npm run build

    - name: Make Windows Zip
      run: zip dist/atom2-win32 dist/win32/x64/atom2.exe dist/win32/x64/WebView2Loader.dll dist/win32/x64/resources.neu

    - name: Make Linux Archive
      run: tar -czvf dist/atom2-linux.tar.gz dist/linux/x64/atom2 dist/linux/x64/resources.neu

    - name: Make Darwin Zip
      run: zip dist/atom2-darwin dist/darwin/x64/atom2.exe dist/darwin/x64/resources.neu

    - name: Update/Create Continous Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "nightly"
        prerelease: true
        title: "Atom2 Nightly x64"
        files: |
          ./dist/atom2-linux.tar.gz
          ./dist/atom2-win32.zip
          ./dist/atom2-darwin.zip
